# Generated by Django 2.1.4 on 2018-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emaili',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emailp',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rollno',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
