# Generated by Django 2.1.4 on 2018-12-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181214_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emaili',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
